config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  def employee_id_less
    employeeid.from(6)
  end

  def self.employee_search(search)
    if search 
      array_desc = Array.new(search.split.size, "lname Like ?").join(" AND ")
      searchArray = ([array_desc,  ("%" + search.split.join("%,%") + "%").split(",")]).flatten
      Employee.where(searchArray)
    else
      #Employee.where.not(status: "not").order(:employee_id_less)
      Employee.order(:employee_id_less)
    end
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @emp_count = Employee.count
    @employees = Employee.employee_search(params[:search])
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
      if @employee.update(employee_params)
        redirect_to employees_path
      else
        render :edit, status: :unprocessable_entity
      end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:lname, :sname, :name, :first, :last, :email, :empid, :startdate, :dept, :paytype, :badgeno, :ext, :telephone, :cell, :pic)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
     @todos = Todo.order(:status, :category, :created_date)
    #@todos = Todo.where(status: "open")

  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)
      if @todo.save
         redirect_to todos_path
 
      else
         render :new 
        
      end
   
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
      if @todo.update(todo_params)
        redirect_to todos_path, notice: 'Todo was successfully updated.' 
      else
        render :edit 
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:category, :subject, :desc, :priority, :name, :tel, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/employees/_employee.html.erb
<tr>
  <td><%= employee.lname %></td>
  <td><%= employee.first %></td>
  <td><%= employee.last %></td>
  <td><%= employee.email %></td>
  <td><%= employee.first.downcase %>.<%= employee.last.downcase %></td>
  <td><%= employee.first.upcase %>.<%= employee.last.upcase %></td>
  <td><%= employee.empid %></td>
  <td><%= employee.startdate %></td>
  <td><%= employee.dept %></td>
  <td><%= employee.paytype %></td>
  <td><%= employee.badgeno %></td>
  <td><%= employee.ext %></td>
  <td><%= employee.telephone %></td>
  <td><%= employee.cell %></td>
  <td><%= employee.pic %></td>
  <td><%= link_to 'Show', employee %></td>
  <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
  <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>

</tr>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="card text-dark bg-light mb-3 border-dark" style="max-width: 30rem;">
  <h1 class="card-header">New / Edit Employee</h1>
  <div class="card-body">

  <div class="field form-group text-primary fw-bold">
    <%= form.label :lname %> 
    <%= form.text_field :lname , class:"form-control", placeholder:"lname" %>
  </div>

  <div class="field form-group text-primary fw-bold">
    <%= form.label :first %> 
    <%= form.text_field :first , class:"form-control", placeholder:"fistname" %>
  </div>

  <div class="field form-group text-primary fw-bold">
    <%= form.label :last %> 
    <%= form.text_field :last , class:"form-control", placeholder:"lastname" %>
  </div>

  <div class="field form-group text-primary fw-bold">
    <%= form.label :email %> 
    <%= form.text_field :email , class:"form-control", placeholder: "email" %>
  </div>

  <div class="field form-group text-primary fw-bold">
    <%= form.label :empid %> 
    <%= form.text_field :empid , class:"form-control", placeholder:"empid" %>
  </div>

  <div class="field form-group text-primary fw-bold">
    <%= form.label :startdate %> 
    <%= form.text_field :startdate , class:"form-control", placeholder:"startdate" %>
  </div>

  <div class="field form-group text-primary fw-bold" >
    <%= form.label :dept %> 
    <%= form.text_field :dept , class:"form-control", placeholder:"department" %>
  </div>

  <div class="field form-group text-primary fw-bold" >
    <%= form.label :paytype %> 
    <%= form.text_field :paytype , class:"form-control", placeholder:"paytype" %>
  </div>
  
  <div class="field form-group text-primary fw-bold" >
    <%= form.label :badgeno %> 
    <%= form.text_field :badgeno , class:"form-control", placeholder:"badgeno" %>
  </div>

  <div class="field form-group text-primary fw-bold" >
    <%= form.label :ext %> 
    <%= form.text_field :ext , class:"form-control", placeholder:"ext" %>
  </div>

  <div class="field form-group text-primary fw-bold" >
    <%= form.label :telephone %> 
    <%= form.text_field :telephone , class:"form-control", placeholder:"telephone" %>
  </div>

  <div class="field form-group text-primary fw-bold" >
    <%= form.label :cell %> 
    <%= form.text_field :cell , class:"form-control", placeholder:"cell" %>
  </div>

  <div class="field form-group text-primary fw-bold" >
    <%= form.label :pic %> 
    <%= form.text_field :pic , class:"form-control", placeholder:"pic" %>
  </div>



  
  </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/index.html.erb
<%= link_to 'New Employee', new_employee_path %>
<span> - Number of Employees = <%= @emp_count %> </span>

<table class="table table-striped table-hover">
<thead>
  <tr>
    <th>lname</th>

    <th>first</th>
    <th>last</th>
    <th>email</th>
    <th>empid</th>
    <th>startdate</th>
    <th>dept</th>
    <th>paytype</th>
    <th>badgeno</th>
    <th>ext</th>
    <th>telephone</th>
    <th>cell</th>
    <th>pic</th>
    <th colspan="3"></th>
  </tr>
</thead>

  <tbody>
  <% @employees.each do |employee| %>
    <%= render employee %>
  <% end %>

</tbody>
</table>

app/views/employees/new.html.erb
<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> |
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>

app/views/layouts/_nav.html.erb

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Career", employees_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'Employee ', employees_path , class: "nav-link active" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Todo ', todos_path , class: "nav-link active" %>
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item">
        </li>
      </ul>
      <%= form_tag(employees_path, :method => "get" , class: "d-flex" ) do %>

        <%= text_field_tag(:search) %>
        <%= submit_tag("Search" , class: "btn btn-outline-success" ) %>
      <% end %>
      



  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Career02</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container-fluid">
    <%= render "layouts/nav"  %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

</br>

<div class="card text-dark bg-light mb-3 border-dark" style="max-width: 30rem;">
  <h1 class="card-header">New / Edit Todo</h1>
  <div class="card-body">

  <div class="field form-group text-primary fw-bold">
    <%= form.label :category %>
    <%= form.text_field :category, class:"form-control", placeholder:"category" %>
  </div>

  <div class="field form-group text-primary fw-bold">
    <%= form.label :subject %>
    <%= form.text_field :subject, class:"form-control", placeholder:"subject" %>
  </div>

  <div class="field form-group text-primary fw-bold">
    <%= form.label :desc %>
    <%= form.text_field :desc, class:"form-control", placeholder:"description" %>
  </div>

  <div class="field form-group text-primary fw-bold">
    <%= form.label :priority %>
    <%= form.text_field :priority , class:"form-control", placeholder:"priority"%>
  </div>

  <div class="field form-group text-primary fw-bold">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"name" %>
  </div>

  <div class="field form-group text-primary fw-bold">
    <%= form.label :tel %>
    <%= form.text_field :tel, class:"form-control", placeholder:"telephone" %>
  </div>

  <div class="field form-group text-primary fw-bold">
    <%= form.label :status %>
    <%= form.text_field :status, class:"form-control", placeholder:"status" %>
  </div>

</div>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
  <p>
    <strong>Category:</strong>
    <%= todo.category %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= todo.subject %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= todo.desc %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= todo.priority %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= todo.name %>
  </p>

  <p>
    <strong>Tel:</strong>
    <%= todo.tel %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= todo.status %>
  </p>

</div>

app/views/todos/edit.html.erb
<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<%= link_to 'New Todo', new_todo_path %>

<table class="table table-striped table-hover" >
  <thead>
    <tr>
      <%
=begin%>
 <th>Date</th> 
<%
=end%>
      <th>Date</th>
      <th>Category</th>
      <th>Subject</th>
      <th>Desc</th>
      <th>Priority</th>
      <th>Name</th>
      <th>Tel</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <%
=begin%>
 <td><%= todo.created_at.strftime("%m-%d-%y - %H:%M %P")  %></td> 
<%
=end%>

        <td><%= todo.created_at.strftime("%m-%d-%y - %H:%M %P")  %></td> 
        <td><%= todo.category %></td>
        <td><%= todo.subject %></td>
        <td><%= todo.desc %></td>
        <td><%= todo.priority %></td>
        <td><%= todo.name %></td>
        <td><%= todo.tel %></td>
        <td><%= todo.status %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @todo.category %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @todo.subject %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @todo.desc %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @todo.priority %>
</p>

<p>
  <strong>Name:</strong>
  <%= @todo.name %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @todo.tel %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todo.status %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>